name: Build and Test Image

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Generate metadata
        id: metadata
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/chart-tests

      - name: Build
        uses: docker/build-push-action@v2.7.0
        with:
          load: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.0 # renovate: python

      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt

      - run: docker images

      - name: Test
        run: pytest --verbose
