name: Build and Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Generate metadata
        id: metadata
        uses: docker/metadata-action@v3.8.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/chart-tests

      - name: Build
        uses: docker/build-push-action@v2.10.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.10.7 # renovate: python

      - name: Install Python dependencies
        run: pip install -r tests/requirements.txt

      - name: Test
        run: pytest -v --image ${{ steps.metadata.outputs.tags }}
