name: Build and Test Image

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Generate metadata
        id: metadata
        uses: docker/metadata-action@v3.6.0
        with:
          images: ghcr.io/${{ github.repository_owner	}}/chart-tests
          # tags: |
          #   type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
