name: Build and Push Docker image

on: push

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/sebastien-prudhomme/chart-tests

      - name: Login to registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
