# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: Docker CD

on: push

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: sebastien-prudhomme/github-actions-for-packages/tic-tac-toe
        tag_with_sha: true
